group = "org.konigsoftware"
version = "1.0.0"

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.konigsoftware"
            artifactId = "konig-kontext"
            version = "1.0.0"

            from(components["java"])
        }
    }
}

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.6.21"
    id("maven-publish")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    /* GENERATED BY GRADLE INIT */

    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:31.0.1-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    /* MANUALLY ADDED */

    implementation("io.grpc:grpc-kotlin-stub:1.3.0")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.6.21")
    implementation("com.google.protobuf:protobuf-java-util:3.24.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
}
