name: Gradle Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: ['8', '11', '17']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'gradle'

    - name: Build Library
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: |
          ./gradlew build

    - name: Publish to Maven Local
      run: ./gradlew publishToMavenLocal
