name: tests-integration

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish to Maven local
        run: ./gradlew publishToMavenLocal

      - name: Install grpcurl
        run: curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v1.8.6/grpcurl_1.8.6_linux_x86_64.tar.gz" | tar -xz -C /usr/local/bin

      - name: Run services
        run: cd examples && ./run_services all

      - name: Run tests
        run: ./gradlew integrationTest

      - name: Dump logs Kotlin
        if: always()
        run: cd examples && ./run_services logdump kotlin

      - name: Dump logs Java
        if: always()
        run: cd examples && ./run_services logdump java
